version: '3.9'

services:
  spark:
    image: bitnami/spark:3.5.5
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    volumes:
      - .:/home/jovyan
    user: root
    ports:
      - "7077:7077"
    networks:
      - sparknet

  spark-worker:
    image: bitnami/spark:3.5.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    volumes:
      - .:/home/jovyan
    user: root
    depends_on:
      - spark
    networks:
      - sparknet

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    command: /home/jovyan/start.sh
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    environment:
      DOCKER_STACKS_JUPYTER_CMD: notebook
      GRANT_SUDO: "yes"
    user: root
    depends_on:
      - spark
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
